PHP-109- Added isArchived and setArchived and passed tests
G4MAlexVannorsdall/php-shopping-list pull request #8
Opened 2022-05-31 13:16 UTC by G4MAlexVannorsdall

## Description
I have updated the ShoppingList class with isArchived and setArchived, then went through the ShoppingList class tests, making sure that they all pass. Also added the test for the setter to make sure if a list is set archived to true it will pass. 

## How to run
Checkout as normal, using the terminal.

## Implementation
Help from you and going through older code.

## Thoughts/Considerations
I decided to make isArchived optional and the default value false.

2022-05-31 15:15 UTC, lindyhopchris requested changes
Good job on this, the getter and setter looks good. I've put some comments and some required changes - which are new things to learn rather than any problems with the code.

2022-05-31 15:15 UTC, lindyhopchris commented on src/Domain/ShoppingList.php
> +        $this->isArchived = $isArchived;
Suggestion: really minor point, we would tend to assign these in the order they are arguments for the constructor. I.e. the `$this->isArchived` assignment should got above the `$this->items` assignment.

2022-05-31 15:15 UTC, lindyhopchris commented on tests/Unit/Domain/ShoppingListTest.php
> +            'My List'
Comment: the trailing comma should not have been removed here. It's good not to change lines that have nothing to do with your changes, plus the trailing comma here is correct.

2022-05-31 15:15 UTC, lindyhopchris commented on src/Domain/ShoppingList.php
> +    public function setArchived(bool $isArchived): void
Required: good job on adding the setter, this is correct! Just one change required. The `setName()` method does `return $this`. We'd expect setters on the class to be consistent, so you should also do the same for this method.

2022-05-31 15:15 UTC, lindyhopchris commented on tests/Unit/Domain/ShoppingListTest.php
> +        $list->setArchived(true);
Required: once you've made the change to what the setter returns, this line needs to assert that the list is returned by the setter, i.e.:

```php
$this->assertSame($list, $list->setArchived(true));
```

You'll see the same pattern in the test for `setName()`.

2022-05-31 15:15 UTC, lindyhopchris commented on src/Domain/ShoppingList.php
> +    public function setArchived(bool $isArchived): void
Just so you know, the reason for returning `$this` from setters is it allows calling code to use method "chaining". I.e. if I needed to set both the name and archived state I can do:

```php
$list->setName('My Groceries')->setArchived(true);
```

Whereas if we didn't return `$this` from the setters, that code would have to be written:

```php
$list->setName('My Groceries');
$list->setArchived(true);
```

Which gets very repetitive if there's lots of things to set! Just so you know, a "chaining" pattern is a developer choice - i.e. to implement it or not is down to the developer. However, once the pattern is in use on a class (as it is on this class' `setName()` method) the class should consistently implement the pattern.

2022-06-01 14:12 UTC, lindyhopchris requested changes
Unfortunately your changes have broken the `setArchived()` method, and this wasn't picked up because you've modified the set archived test so that it is no longer valid. My comments should point you in the right direction!

2022-06-01 14:12 UTC, lindyhopchris commented on src/Domain/ShoppingList.php
> +       return $this;
Required: this method no longer works.

2022-06-01 14:12 UTC, lindyhopchris commented on tests/Unit/Domain/ShoppingListTest.php
> +        $this->assertSame($list, $list->setArchived(false));
Required: the test here is not set up correctly, which is why you've not picked up on the code in `setArchived()` no longer working. You already know that a list starts off with archived as `false` - so setting it to `false` doesn't change anything.

Given: a shopping list that is not archived...
When: I set the archived flag to `true`
Then: it is archived (indicated by `isArchived()` returning `true`).

2022-06-01 14:12 UTC, lindyhopchris commented on tests/Unit/Domain/ShoppingListTest.php
> +        $this->assertSame(false, $list->isArchived());
Suggestion: PHPUnit has two helper assertions for true and false - `assertTrue($actual)` and `assertFalse($actual)`.

2022-06-01 16:31 UTC, lindyhopchris requested changes
I think we should chat about this on Monday morning, because we're circling around the solution rather than reaching it. I'm not entirely sure why so it might be better to discuss rather than going back and forth on the PR? I'll drop you an invite for Monday morning to discuss.

2022-06-01 16:31 UTC, lindyhopchris commented on src/Domain/ShoppingList.php
> +        if (!empty($isArchived)) {
Question: not sure why you've put this in? Should we conditionally be setting the value, or should it just be set to the value that is given to the function (which is already type-hinted as `bool`)?

2022-06-01 16:31 UTC, lindyhopchris commented on tests/Unit/Domain/ShoppingListTest.php
> +        $this->assertTrue(true);
Required: here you are asserting that true is true, which is always going to pass. You should be asserting that the list is archived.

2022-06-10 09:05 UTC, G4MAlexVannorsdall commented
Pushed the changes to the code we worked on this morning.

2022-06-10 11:46 UTC, lindyhopchris approved these changes

2022-06-10 11:46 UTC, merged